<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="HelperServiceServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/HelperServiceServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/HelperServiceServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://HelperService.ws">
    <import location="http://localhost:8080/BPELHelperService/HelperServiceService?wsdl" namespace="http://HelperService.ws"/>
    <plnk:partnerLinkType name="HelperServiceLinkType">
        <plnk:role name="HelperRole" portType="ns:HelperServicePortType"/>
    </plnk:partnerLinkType>
</definitions>
