<?xml version="1.0" encoding="UTF-8"?>
<definitions name="LameDuckWSDL" targetNamespace="http://LameDuck.ws"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://LameDuck.ws" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://LameDuck.ws" xmlns:tns="http://LameDuck.ws">
            <xsd:complexType name="FlightInfoType">
                <xsd:sequence minOccurs="1" maxOccurs="1">
                    <xsd:element name="bookingNumber" type="xsd:string"></xsd:element>
                    <xsd:element name="flightPrice" type="xsd:int"></xsd:element>
                    <xsd:element name="airlineReservationServiceName" type="xsd:string"></xsd:element>
                    <xsd:element name="flight" type="tns:FlightType"></xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="FlightType">
                <xsd:sequence>
                    <xsd:element name="startAirport" type="xsd:string"></xsd:element>
                    <xsd:element name="destinationAirport" type="xsd:string"></xsd:element>
                    <xsd:element name="liftoffDate" type="xsd:date"></xsd:element>
                    <xsd:element name="landingDate" type="xsd:date"></xsd:element>
                    <xsd:element name="carrierName" type="xsd:string"></xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="FlightFaultType">
                <xsd:sequence>
                    <xsd:element name="fault_message" type="xsd:string"></xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="FlightFault" type="tns:FlightFaultType"></xsd:element>
            <xsd:element name="getFlightsRequest">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="action" type="xsd:string"></xsd:element>
                        <xsd:element name="startDestination" type="xsd:string"></xsd:element>
                        <xsd:element name="finalDestination" type="xsd:string"></xsd:element>
                        <xsd:element name="dateFlight" type="xsd:date"></xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="bookFlightRequest">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="action" type="xsd:string"></xsd:element>
                        <xsd:element name="bookingNumber" type="xsd:string"></xsd:element>
                        <xsd:element name="CreditCardInformation" type="tns:CreditCardInformationType"></xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="cancelFlightRequest">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="action" type="xsd:string"></xsd:element>
                        <xsd:element name="bookingNumber" type="xsd:string"></xsd:element>
                        <xsd:element name="price" type="xsd:int"></xsd:element>
                        <xsd:element name="CreditCardInformation" type="tns:CreditCardInformationType"></xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:complexType name="CreditCardInformationType">
                <xsd:sequence>
                    <xsd:element name="holderName" type="xsd:string"></xsd:element>
                    <xsd:element name="eightDigitNumber" type="xsd:string"></xsd:element>
                    <xsd:element name="expirationDate" type="xsd:date"></xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="bookFlightResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="response" type="xsd:boolean"></xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="cancelFlightResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="response" type="xsd:boolean"></xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="getFlightsResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="FlightInfoList" type="tns:FlightInfoType" maxOccurs="unbounded" minOccurs="0"></xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
    </types>
    <message name="getFlightsRequest">
        <part name="request" element="tns:getFlightsRequest"/>
    </message>
    <message name="getFlightsResponse">
        <part name="response" element="tns:getFlightsResponse"/>
    </message>
    <message name="bookFlightRequest">
        <part name="request" element="tns:bookFlightRequest"/>
    </message>
    <message name="bookFlightResponse">
        <part name="response" element="tns:bookFlightResponse"/>
    </message>
    <message name="bookFlightFault">
        <part name="fault_message" element="tns:FlightFault"/>
    </message>
    <message name="cancelFlightRequest">
        <part name="request" element="tns:cancelFlightRequest"/>
    </message>
    <message name="cancelFlightResponse">
        <part name="response" element="tns:cancelFlightResponse"/>
    </message>
    <message name="cancelFlightFault">
        <part name="fault_message" element="tns:FlightFault"/>
    </message>
    <portType name="LameDuck">
        <operation name="getFlights">
            <input name="input1" message="tns:getFlightsRequest"/>
            <output name="output1" message="tns:getFlightsResponse"/>
        </operation>
        <operation name="bookFlight">
            <input name="input2" message="tns:bookFlightRequest"/>
            <output name="output2" message="tns:bookFlightResponse"/>
            <fault name="fault1" message="tns:bookFlightFault"/>
        </operation>
        <operation name="cancelFlight">
            <input name="input3" message="tns:cancelFlightRequest"/>
            <output name="output3" message="tns:cancelFlightResponse"/>
            <fault name="fault1" message="tns:cancelFlightFault"/>
        </operation>
    </portType>
    <binding name="LameDuckBinding" type="tns:LameDuck">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="getFlights">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="bookFlight">
            <soap:operation/>
            <input name="input2">
                <soap:body use="literal"/>
            </input>
            <output name="output2">
                <soap:body use="literal"/>
            </output>
            <fault name="fault1">
                <soap:fault name="fault1" use="literal"/>
            </fault>
        </operation>
        <operation name="cancelFlight">
            <soap:operation/>
            <input name="input3">
                <soap:body use="literal"/>
            </input>
            <output name="output3">
                <soap:body use="literal"/>
            </output>
            <fault name="fault1">
                <soap:fault name="fault1" use="literal"/>
            </fault>
        </operation>
    </binding>
    <service name="LameDuckWSDLService">
        <port name="LameDuckBindingPort" binding="tns:LameDuckBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/service"/>
        </port>
    </service>
</definitions>
